# CodeRabbit 설정 - Chinchilla 프로젝트
language: ko

reviews:
  # 자동 리뷰 활성화
  auto_review:
    enabled: true
    drafts: false
    # ✅ 핵심: 모든 브랜치 명시
    base_branches:
      - "**"  # 모든 브랜치
  
  # ✅ 추가: 명시적으로 모든 브랜치 허용
  all_branches: true
  
  profile: chill
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  request_changes_workflow: false
  
  # 파일 패턴
  path_filters:
    - "**/*.java"
    - "**/*.py"
    - "**/*.gradle"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.md"
  
  # 제외 패턴
  path_ignore:
    - "**/node_modules/**"
    - "**/build/**"
    - "**/__pycache__/**"
    - "**/data/chroma_*/**"
  
  # 파일별 지침
  path_instructions:
    - path: "**/*.java"
      instructions: |
        - Java 21 및 Spring Boot 3.2 베스트 프랙티스
        - 보안 취약점 체크
    
    - path: "**/*.py"
      instructions: |
        - Python 3.11+ 코딩 스타일 (PEP 8)
        - RAG 파이프라인 로직 검토
        - Upstage API 최적화

chat:
  auto_reply: true

early_access: false
enable_free_tier: true
```

---

## 🎯 지금 바로 할 일

### 1. 화면 아래로 스크롤

맨 아래 **"Apply Changes"** 버튼이 보일 거예요!
```
┌──────────────────────────────┐
│  [Apply Changes]             │  ← 주황색 버튼 클릭!
└──────────────────────────────┘
