spring:
  application:
    name: chinchilla-web

  # ??????
  datasource:
    url: jdbc:mysql://localhost:3307/chinchilla?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update  # create: ??? ???, update: ?? ????
    show-sql: true      # SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true          # SQL ?? ??
        dialect: org.hibernate.dialect.MySQLDialect

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # ??: false, ????: true
    encoding: UTF-8

  # ?? ??? (???)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ?? ??
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ?? ??
logging:
  level:
    root: INFO
    com.chinchilla: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Python RAG ???
python:
  rag:
    url: http://localhost:8000